"""add uq constraint to tags

Revision ID: 06402b04a191
Revises: 3ef82601c18c
Create Date: 2025-11-23 22:39:18.231667

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06402b04a191"
down_revision: Union[str, Sequence[str], None] = "3ef82601c18c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_tags_agent_run_value", "tags", ["agent_run_id", "value"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_tags_agent_run_value", "tags", type_="unique")
    # ### end Alembic commands ###
