"""Associate chat conversations with collections

Revision ID: 0a5c90ee3e39
Revises: 7a05c9d5804c
Create Date: 2025-12-11 10:24:44.605347

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a5c90ee3e39"
down_revision: Union[str, Sequence[str], None] = "7a05c9d5804c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # We're changing the format of context_serialized, so old sessions are incompatible
    op.execute("DELETE FROM chat_sessions WHERE context_serialized IS NOT NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_sessions", sa.Column("collection_id", sa.String(length=36), nullable=True))
    op.add_column(
        "chat_sessions", sa.Column("estimated_messages_tokens", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_chat_sessions__collection_id"), "chat_sessions", ["collection_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_chat_sessions__collection_id__collections"),
        "chat_sessions",
        "collections",
        ["collection_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_chat_sessions__collection_id__collections"), "chat_sessions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_chat_sessions__collection_id"), table_name="chat_sessions")
    op.drop_column("chat_sessions", "estimated_messages_tokens")
    op.drop_column("chat_sessions", "collection_id")
    # ### end Alembic commands ###
