"""add collection id to label sets

Revision ID: 129f8ef65f56
Revises: 80ddc51ed584
Create Date: 2025-10-25 02:02:37.769473

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "129f8ef65f56"
down_revision: Union[str, Sequence[str], None] = "80ddc51ed584"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("label_sets", sa.Column("collection_id", sa.String(length=36), nullable=False))
    op.create_index(
        op.f("ix_label_sets__collection_id"), "label_sets", ["collection_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_label_sets__collection_id__collections"),
        "label_sets",
        "collections",
        ["collection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_label_sets__collection_id__collections"), "label_sets", type_="foreignkey"
    )
    op.drop_index(op.f("ix_label_sets__collection_id"), table_name="label_sets")
    op.drop_column("label_sets", "collection_id")
    # ### end Alembic commands ###
