"""drop old telemetry accumulation index

Revision ID: 1f06faa655c4
Revises: 7575b151dce9
Create Date: 2025-11-18 23:05:11.221212

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f06faa655c4"
down_revision: Union[str, Sequence[str], None] = "7575b151dce9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.get_context().autocommit_block():
        op.drop_index(
            op.f("idx_telemetry_accumulation_key_type"),
            table_name="telemetry_accumulation",
            postgresql_concurrently=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.create_index(
            op.f("idx_telemetry_accumulation_key_type"),
            "telemetry_accumulation",
            ["key", "data_type"],
            unique=False,
            postgresql_concurrently=True,
        )
    # ### end Alembic commands ###
