"""remove text_for_search

Revision ID: 2ce051f8d590
Revises: 4d619a150245
Create Date: 2025-11-05 18:10:16.551919

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ce051f8d590"
down_revision: Union[str, Sequence[str], None] = "4d619a150245"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_runs", "text_for_search")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
