"""add created_at to transcripts and transcript groups

Revision ID: 312d3aece250
Revises: d9a6d9d73774
Create Date: 2025-08-18 17:24:41.301225

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import func

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "312d3aece250"
down_revision: Union[str, Sequence[str], None] = "d9a6d9d73774"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server_default for new rows and populate existing rows
    op.add_column(
        "transcript_groups",
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=func.now()),
    )
    op.add_column(
        "transcripts",
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=func.now()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transcripts", "created_at")
    op.drop_column("transcript_groups", "created_at")
    # ### end Alembic commands ###
