"""add telemetry lineage

Revision ID: 3769d80f60b2
Revises: 1046850ac3c7
Create Date: 2025-11-29 02:00:33.481046

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3769d80f60b2"
down_revision: Union[str, Sequence[str], None] = "1046850ac3c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telemetry_lineage",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("collection_id", sa.String(length=36), nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("derived_type", sa.String(length=32), nullable=False),
        sa.Column("derived_id", sa.String(length=128), nullable=False),
        sa.Column("derived_key", sa.String(length=64), nullable=True),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=True),
        sa.Column("source_idx", sa.Integer(), nullable=True),
        sa.Column("source_transcript_id", sa.String(length=64), nullable=True),
        sa.Column("telemetry_log_id", sa.String(length=36), nullable=True),
        sa.Column("telemetry_accumulation_id", sa.String(length=36), nullable=True),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telemetry_lineage")),
        sa.UniqueConstraint(
            "collection_id",
            "agent_run_id",
            "derived_type",
            "derived_id",
            "derived_key",
            "source_type",
            "source_id",
            "source_idx",
            name="uq_telemetry_lineage_composite",
        ),
    )
    op.create_index(
        op.f("ix_telemetry_lineage__agent_run_id"),
        "telemetry_lineage",
        ["agent_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_telemetry_lineage__agent_run_id__derived_type",
        "telemetry_lineage",
        ["agent_run_id", "derived_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_lineage__collection_id"),
        "telemetry_lineage",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_lineage__created_at"), "telemetry_lineage", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_telemetry_lineage__derived_id"), "telemetry_lineage", ["derived_id"], unique=False
    )
    op.create_index(
        "ix_telemetry_lineage__derived_type__derived_id",
        "telemetry_lineage",
        ["derived_type", "derived_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_lineage__source_id"), "telemetry_lineage", ["source_id"], unique=False
    )
    op.create_index(
        "ix_telemetry_lineage__telemetry_accumulation_id",
        "telemetry_lineage",
        ["telemetry_accumulation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_lineage__telemetry_log_id"),
        "telemetry_lineage",
        ["telemetry_log_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_telemetry_lineage__telemetry_log_id"), table_name="telemetry_lineage")
    op.drop_index("ix_telemetry_lineage__telemetry_accumulation_id", table_name="telemetry_lineage")
    op.drop_index(op.f("ix_telemetry_lineage__source_id"), table_name="telemetry_lineage")
    op.drop_index("ix_telemetry_lineage__derived_type__derived_id", table_name="telemetry_lineage")
    op.drop_index(op.f("ix_telemetry_lineage__derived_id"), table_name="telemetry_lineage")
    op.drop_index(op.f("ix_telemetry_lineage__created_at"), table_name="telemetry_lineage")
    op.drop_index(op.f("ix_telemetry_lineage__collection_id"), table_name="telemetry_lineage")
    op.drop_index(
        "ix_telemetry_lineage__agent_run_id__derived_type", table_name="telemetry_lineage"
    )
    op.drop_index(op.f("ix_telemetry_lineage__agent_run_id"), table_name="telemetry_lineage")
    op.drop_table("telemetry_lineage")
    # ### end Alembic commands ###
