"""add tags table + crud

Revision ID: 3ef82601c18c
Revises: 2cbd1a8d1894
Create Date: 2025-11-22 17:13:12.557818

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ef82601c18c"
down_revision: Union[str, Sequence[str], None] = "2cbd1a8d1894"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("collection_id", sa.String(length=36), nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_tags__agent_run_id__agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_tags__collection_id__collections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_tags__created_by__users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
    )
    op.create_index(op.f("ix_tags__agent_run_id"), "tags", ["agent_run_id"], unique=False)
    op.create_index(op.f("ix_tags__collection_id"), "tags", ["collection_id"], unique=False)
    op.create_index(op.f("ix_tags__created_by"), "tags", ["created_by"], unique=False)
    op.create_index(
        "ix_tags_collection_agent_run", "tags", ["collection_id", "agent_run_id"], unique=False
    )
    op.create_index("ix_tags_collection_value", "tags", ["collection_id", "value"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tags_collection_value", table_name="tags")
    op.drop_index("ix_tags_collection_agent_run", table_name="tags")
    op.drop_index(op.f("ix_tags__created_by"), table_name="tags")
    op.drop_index(op.f("ix_tags__collection_id"), table_name="tags")
    op.drop_index(op.f("ix_tags__agent_run_id"), table_name="tags")
    op.drop_table("tags")
    # ### end Alembic commands ###
