"""cascade agent run deletes

Revision ID: 44aa3e803cca
Revises: 9d7efd738657
Create Date: 2025-09-10 00:44:02.023028

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44aa3e803cca"
down_revision: Union[str, Sequence[str], None] = "9d7efd738657"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_transcript_groups__agent_run_id__agent_runs"),
        "transcript_groups",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_transcript_groups__agent_run_id__agent_runs"),
        "transcript_groups",
        "agent_runs",
        ["agent_run_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("fk_transcripts__agent_run_id__agent_runs"), "transcripts", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_transcripts__agent_run_id__agent_runs"),
        "transcripts",
        "agent_runs",
        ["agent_run_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_transcripts__agent_run_id__agent_runs"), "transcripts", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_transcripts__agent_run_id__agent_runs"),
        "transcripts",
        "agent_runs",
        ["agent_run_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("fk_transcript_groups__agent_run_id__agent_runs"),
        "transcript_groups",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_transcript_groups__agent_run_id__agent_runs"),
        "transcript_groups",
        "agent_runs",
        ["agent_run_id"],
        ["id"],
    )
    # ### end Alembic commands ###
