"""rm investigator

Revision ID: 45642a30c03f
Revises: 9a1c94e22cbb
Create Date: 2026-01-10 13:50:23.342944

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45642a30c03f"
down_revision: Union[str, Sequence[str], None] = "9a1c94e22cbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables in dependency order to satisfy foreign keys.
    op.drop_index(
        op.f("ix_counterfactual_experiment_results__collection_id"),
        table_name="counterfactual_experiment_results",
    )
    op.drop_index(
        op.f("ix_counterfactual_experiment_results__experiment_config_id"),
        table_name="counterfactual_experiment_results",
    )
    op.drop_table("counterfactual_experiment_results")
    op.drop_index(
        op.f("ix_simple_rollout_experiment_results__collection_id"),
        table_name="simple_rollout_experiment_results",
    )
    op.drop_index(
        op.f("ix_simple_rollout_experiment_results__experiment_config_id"),
        table_name="simple_rollout_experiment_results",
    )
    op.drop_table("simple_rollout_experiment_results")
    op.drop_table("simple_rollout_experiment_config_backends")
    op.drop_table("simple_rollout_config_anthropic_backends")
    op.drop_index(
        op.f("ix_simple_rollout_experiment_configs__base_context_id"),
        table_name="simple_rollout_experiment_configs",
    )
    op.drop_index(
        op.f("ix_simple_rollout_experiment_configs__deleted_at"),
        table_name="simple_rollout_experiment_configs",
    )
    op.drop_index(
        op.f("ix_simple_rollout_experiment_configs__judge_config_id"),
        table_name="simple_rollout_experiment_configs",
    )
    op.drop_index(
        op.f("ix_simple_rollout_experiment_configs__workspace_id"),
        table_name="simple_rollout_experiment_configs",
    )
    op.drop_table("simple_rollout_experiment_configs")
    op.drop_index(
        op.f("ix_counterfactual_experiment_configs__anthropic_compati_40a5"),
        table_name="counterfactual_experiment_configs",
    )
    op.drop_index(
        op.f("ix_counterfactual_experiment_configs__base_context_id"),
        table_name="counterfactual_experiment_configs",
    )
    op.drop_index(
        op.f("ix_counterfactual_experiment_configs__deleted_at"),
        table_name="counterfactual_experiment_configs",
    )
    op.drop_index(
        op.f("ix_counterfactual_experiment_configs__idea_id"),
        table_name="counterfactual_experiment_configs",
    )
    op.drop_index(
        op.f("ix_counterfactual_experiment_configs__judge_config_id"),
        table_name="counterfactual_experiment_configs",
    )
    op.drop_index(
        op.f("ix_counterfactual_experiment_configs__openai_compatible_f0be"),
        table_name="counterfactual_experiment_configs",
    )
    op.drop_index(
        op.f("ix_counterfactual_experiment_configs__workspace_id"),
        table_name="counterfactual_experiment_configs",
    )
    op.drop_table("counterfactual_experiment_configs")
    op.drop_index(op.f("ix_experiment_ideas__deleted_at"), table_name="experiment_ideas")
    op.drop_index(op.f("ix_experiment_ideas__workspace_id"), table_name="experiment_ideas")
    op.drop_table("experiment_ideas")
    op.drop_index(op.f("ix_base_contexts__deleted_at"), table_name="base_contexts")
    op.drop_index(op.f("ix_base_contexts__workspace_id"), table_name="base_contexts")
    op.drop_table("base_contexts")
    op.drop_index(
        op.f("ix_tmp_investigator_authorized_users__user_id"),
        table_name="tmp_investigator_authorized_users",
    )
    op.drop_table("tmp_investigator_authorized_users")
    op.drop_index(
        op.f("ix_anthropic_compatible_backends__deleted_at"),
        table_name="anthropic_compatible_backends",
    )
    op.drop_index(
        op.f("ix_anthropic_compatible_backends__workspace_id"),
        table_name="anthropic_compatible_backends",
    )
    op.drop_table("anthropic_compatible_backends")
    op.drop_index(op.f("ix_judge_configs__deleted_at"), table_name="judge_configs")
    op.drop_index(op.f("ix_judge_configs__workspace_id"), table_name="judge_configs")
    op.drop_table("judge_configs")
    op.drop_index(
        op.f("ix_openai_compatible_backends__deleted_at"), table_name="openai_compatible_backends"
    )
    op.drop_index(
        op.f("ix_openai_compatible_backends__workspace_id"), table_name="openai_compatible_backends"
    )
    op.drop_table("openai_compatible_backends")
    op.drop_index(
        op.f("ix_investigator_workspaces__created_by"), table_name="investigator_workspaces"
    )
    op.drop_table("investigator_workspaces")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
