"""refinement agent sessions table

Revision ID: 6b2112c87519
Revises: 1ef294fe9b86
Create Date: 2025-08-19 12:28:06.001706

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b2112c87519"
down_revision: Union[str, Sequence[str], None] = "1ef294fe9b86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refinement_agent_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rubric_id", sa.String(length=36), nullable=False),
        sa.Column("rubric_version", sa.Integer(), nullable=False),
        sa.Column("messages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("pending_rubric", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rubric_id", "rubric_version"],
            ["rubrics.id", "rubrics.version"],
            name=op.f("fk_refinement_agent_sessions__rubric_id_rubric_version__rubrics"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refinement_agent_sessions")),
    )
    op.create_index(
        op.f("ix_refinement_agent_sessions__rubric_id"),
        "refinement_agent_sessions",
        ["rubric_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refinement_agent_sessions__rubric_version"),
        "refinement_agent_sessions",
        ["rubric_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refinement_agent_sessions__updated_at"),
        "refinement_agent_sessions",
        ["updated_at"],
        unique=False,
    )
    op.drop_index(op.f("ix_refinement_sessions__collection_id"), table_name="refinement_sessions")
    op.drop_index(op.f("ix_refinement_sessions__rubric_id"), table_name="refinement_sessions")
    op.drop_index(op.f("ix_refinement_sessions__updated_at"), table_name="refinement_sessions")
    op.drop_table("refinement_sessions")
    op.alter_column("jobs", "type", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "jobs",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING", "RUNNING", "CANCELED", "COMPLETED", name="jobstatus"
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
