"""Add model to chat sessions

Revision ID: 8077418780aa
Revises: 68f41a40b203
Create Date: 2025-09-15 12:43:17.976620

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8077418780aa"
down_revision: Union[str, Sequence[str], None] = "68f41a40b203"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_sessions",
        sa.Column("chat_model", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("chat_sessions", sa.Column("estimated_input_tokens", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_sessions", "chat_model")
    op.drop_column("chat_sessions", "estimated_input_tokens")

    # ### end Alembic commands ###
