"""add_unique_constraint_agent_run_label_set

Revision ID: 80ddc51ed584
Revises: cb1d6abb2dd0
Create Date: 2025-10-24 17:42:39.198844

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80ddc51ed584"
down_revision: Union[str, Sequence[str], None] = "cb1d6abb2dd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_label_agent_run_label_set", "labels", ["agent_run_id", "label_set_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_label_agent_run_label_set", "labels", type_="unique")
    # ### end Alembic commands ###
