"""telemetry accumulation

Revision ID: 894f553e5699
Revises: 86d817cb445f
Create Date: 2025-08-26 16:46:09.984880

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "894f553e5699"
down_revision: Union[str, Sequence[str], None] = "86d817cb445f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telemetry_accumulation",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("data_type", sa.Text(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_telemetry_accumulation__user_id__users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telemetry_accumulation")),
    )
    op.create_index(
        "idx_telemetry_accumulation_key_type",
        "telemetry_accumulation",
        ["key", "data_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_accumulation__created_at"),
        "telemetry_accumulation",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_accumulation__data_type"),
        "telemetry_accumulation",
        ["data_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_accumulation__key"), "telemetry_accumulation", ["key"], unique=False
    )
    op.create_index(
        op.f("ix_telemetry_accumulation__user_id"),
        "telemetry_accumulation",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_telemetry_accumulation__user_id"), table_name="telemetry_accumulation")
    op.drop_index(op.f("ix_telemetry_accumulation__key"), table_name="telemetry_accumulation")
    op.drop_index(op.f("ix_telemetry_accumulation__data_type"), table_name="telemetry_accumulation")
    op.drop_index(
        op.f("ix_telemetry_accumulation__created_at"), table_name="telemetry_accumulation"
    )
    op.drop_index("idx_telemetry_accumulation_key_type", table_name="telemetry_accumulation")
    op.drop_table("telemetry_accumulation")
    # ### end Alembic commands ###
