"""Cascade delete for API key usage

Revision ID: 94689d4c6ebe
Revises: 863c43b0ddd3
Create Date: 2025-09-29 14:00:15.640081

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94689d4c6ebe"
down_revision: Union[str, Sequence[str], None] = "863c43b0ddd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_model_usage__api_key_id__model_api_keys"), "model_usage", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_model_usage__api_key_id__model_api_keys"),
        "model_usage",
        "model_api_keys",
        ["api_key_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_model_usage__api_key_id__model_api_keys"), "model_usage", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_model_usage__api_key_id__model_api_keys"),
        "model_usage",
        "model_api_keys",
        ["api_key_id"],
        ["id"],
    )
    # ### end Alembic commands ###
