"""add telemetry logs

Revision ID: b6994ceb6a98
Revises: e68cf49cd5a2
Create Date: 2025-07-31 11:49:13.574780

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6994ceb6a98"
down_revision: Union[str, Sequence[str], None] = "e68cf49cd5a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telemetry_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("collection_id", sa.String(length=36), nullable=True),
        sa.Column("json_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_telemetry_logs__collection_id__collections"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_telemetry_logs__user_id__users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telemetry_logs")),
    )
    op.create_index(
        op.f("ix_telemetry_logs__collection_id"), "telemetry_logs", ["collection_id"], unique=False
    )
    op.create_index(op.f("ix_telemetry_logs__user_id"), "telemetry_logs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_telemetry_logs__user_id"), table_name="telemetry_logs")
    op.drop_index(op.f("ix_telemetry_logs__collection_id"), table_name="telemetry_logs")
    op.drop_table("telemetry_logs")
    # ### end Alembic commands ###
