"""cascade delete

Revision ID: b9b8a49f1b8b
Revises: b19c321c8291
Create Date: 2025-09-04 18:13:26.464273

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9b8a49f1b8b"
down_revision: Union[str, Sequence[str], None] = "b19c321c8291"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_chat_sessions_agent_run_id"), "chat_sessions", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_chat_sessions__agent_run_id__agent_runs"),
        "chat_sessions",
        "agent_runs",
        ["agent_run_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_chat_sessions__agent_run_id__agent_runs"), "chat_sessions", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_chat_sessions_agent_run_id"),
        "chat_sessions",
        "agent_runs",
        ["agent_run_id"],
        ["id"],
    )
    # ### end Alembic commands ###
