"""add frameworks and providers to onboarding

Revision ID: c96af745aa55
Revises: 7d7368f4cc8e
Create Date: 2025-08-15 15:46:14.546778

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c96af745aa55"
down_revision: Union[str, Sequence[str], None] = "7d7368f4cc8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profiles",
        sa.Column("frameworks", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "user_profiles",
        sa.Column("providers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profiles", "providers")
    op.drop_column("user_profiles", "frameworks")
    # ### end Alembic commands ###
