"""labeling

Revision ID: cdf34f57b7b2
Revises: 44aa3e803cca
Create Date: 2025-09-10 11:02:29.106017

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cdf34f57b7b2"
down_revision: Union[str, Sequence[str], None] = "44aa3e803cca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "judge_run_labels",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("agent_run_id", sa.String(length=36), nullable=False),
        sa.Column("label", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rubric_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_judge_run_labels__agent_run_id__agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_judge_run_labels")),
    )
    op.create_index(
        op.f("ix_judge_run_labels__agent_run_id"),
        "judge_run_labels",
        ["agent_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_judge_run_labels__rubric_id"),
        "judge_run_labels",
        ["rubric_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_chat_sessions_judge_result_id"), "chat_sessions", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_chat_sessions__judge_result_id__judge_results"),
        "chat_sessions",
        "judge_results",
        ["judge_result_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_chat_sessions__judge_result_id__judge_results"),
        "chat_sessions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_chat_sessions_judge_result_id"),
        "chat_sessions",
        "judge_results",
        ["judge_result_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_judge_run_labels__rubric_id"), table_name="judge_run_labels")
    op.drop_index(op.f("ix_judge_run_labels__agent_run_id"), table_name="judge_run_labels")
    op.drop_table("judge_run_labels")
    # ### end Alembic commands ###
