"""add agent_run_id to transcript groups

Revision ID: d9a6d9d73774
Revises: b955627d29a6
Create Date: 2025-08-18 17:09:58.217600

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9a6d9d73774"
down_revision: Union[str, Sequence[str], None] = "b955627d29a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transcript_groups", sa.Column("agent_run_id", sa.String(length=36), nullable=False)
    )
    op.create_index(
        op.f("ix_transcript_groups__agent_run_id"),
        "transcript_groups",
        ["agent_run_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_transcript_groups__agent_run_id__agent_runs"),
        "transcript_groups",
        "agent_runs",
        ["agent_run_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_transcript_groups__agent_run_id__agent_runs"),
        "transcript_groups",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_transcript_groups__agent_run_id"), table_name="transcript_groups")
    op.drop_column("transcript_groups", "agent_run_id")
    # ### end Alembic commands ###
