"""add cancelling to jobstatus

Revision ID: fd41be117f90
Revises: 32bc3e96d06f
Create Date: 2025-11-14 14:27:20.319762

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd41be117f90"
down_revision: Union[str, Sequence[str], None] = "32bc3e96d06f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    new_status = "CANCELLING"
    enum_name = "jobstatus"

    with op.get_context().autocommit_block():
        op.execute(f"ALTER TYPE {enum_name} ADD VALUE IF NOT EXISTS '{new_status}'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
